[[OpenVAF]]
arch = "aarch64"
git-tree-sha1 = "ff92b74dae5a6d8e5d09f259616eb8ed654f6381"
os = "macos"

    [[OpenVAF.download]]
    sha256 = "ea93e91827c430a316806ee4800b16acb424f397752019bc6fea9f5b6a0dc31d"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.aarch64-apple-darwin.tar.gz"
[[OpenVAF]]
arch = "aarch64"
git-tree-sha1 = "e03958cd196ba87ba1064b07b4881982f297ab5d"
libc = "glibc"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "ff14b4749a78bcce2cc3ba521ad0077be3af62081bef8a46823464c195287ac7"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.aarch64-linux-gnu.tar.gz"
[[OpenVAF]]
arch = "aarch64"
git-tree-sha1 = "2f3ff4632efbd6e5cdce5fa5c96071a3da9a3872"
libc = "musl"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "f613597fbab4a60177fb7f010ebebe145a203bf15ff0be08bae9dc9e04f5732b"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.aarch64-linux-musl.tar.gz"
[[OpenVAF]]
arch = "i686"
git-tree-sha1 = "9b6b7f198cc6046c93eff26bd028349378f5733e"
libc = "glibc"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "2580a4457a5d4902c129e342b70d979f08a60c0800afb6041cefa62145d44887"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.i686-linux-gnu.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "a6841e979ff127fbedde246fff733ae9078cb85b"
os = "macos"

    [[OpenVAF.download]]
    sha256 = "7f878b0d55af436805cbcd837d9610f5c6f656ac36531f7f3b5e10f26d823353"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.x86_64-apple-darwin.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "c4bd5bb0c69fa4efae69e26d0ba4ef38294cc4cf"
libc = "glibc"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "142f5f56307d95627debd0d411f7afb038f3fc1a55b5db0d295b64ba5adc34e2"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.x86_64-linux-gnu.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "43d824356bd7f9b9e621cc953f8d2fb3285dc220"
libc = "musl"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "1b5cdce4dd37cccf33ede06b9b88cc8f911e5ea6aa89a15ec3279f59a5b484d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.x86_64-linux-musl.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "f7e9ddf0bc3a0fb9f69b9708aa5a8e4bc122f82e"
os = "freebsd"

    [[OpenVAF.download]]
    sha256 = "6cc6cceb3428a51079ac1223dcb931cf1374040a90c18d81fd8d6915664117df"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.x86_64-unknown-freebsd.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "19e2839c42a4ffd8a1b34352c79a90868e8cfaf9"
os = "windows"

    [[OpenVAF.download]]
    sha256 = "521d8b9b268b46599bc0775b2563fd170456c39d3aeca23b5bb74aeadfb38d47"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+1/OpenVAF.v23.5.0.x86_64-w64-mingw32.tar.gz"
