[[OpenVAF]]
arch = "aarch64"
git-tree-sha1 = "987593b21a587ab9d3370b5345228e8ba5f7d8ca"
os = "macos"

    [[OpenVAF.download]]
    sha256 = "013463ddb177133c87ce188939ee2b0dbc9c9e529b6b99caecae3605afbfd88b"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.aarch64-apple-darwin.tar.gz"
[[OpenVAF]]
arch = "aarch64"
git-tree-sha1 = "d9e5371508583d60361c73e5604b1c58ba173185"
libc = "glibc"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "bcaa0c838649746199f9e91c95e66cf6ef085f9c78b0028db4c52f8432118c33"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.aarch64-linux-gnu.tar.gz"
[[OpenVAF]]
arch = "aarch64"
git-tree-sha1 = "66a991549b99f8f528eb25c680cf0b4f7190d5fc"
libc = "musl"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "cb869387a0fd650fba765769e01ee0b90b6b849f174a949e517ade4d5807d241"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.aarch64-linux-musl.tar.gz"
[[OpenVAF]]
arch = "i686"
git-tree-sha1 = "c5e2a064f3e6e5a7d029478b042cd67216fcc582"
libc = "glibc"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "2a34858bccbab1de5286af92e9a151619eaea153ab8cb1887b63fb4219728777"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.i686-linux-gnu.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "e54ddf8720ba724f09ccf255f84ed41d461b20e5"
os = "macos"

    [[OpenVAF.download]]
    sha256 = "76f58bbab4b621d1e59105abedd8f234a66b348590cb570d367e7ef6447aeafa"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.x86_64-apple-darwin.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "67cf1bf1e62f7eceace2ea3d56e8b22c2d47340c"
libc = "glibc"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "ac1f2472784a83996dfac9c1d17557efc5f1ff77885bcaa03546566b62c95f86"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.x86_64-linux-gnu.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "54635dd3c9ab03b74f652e61fefbf6af3cb8b8d7"
libc = "musl"
os = "linux"

    [[OpenVAF.download]]
    sha256 = "ad0e1844f23c732a17958a2d931d430fcc3fab6af889630f6cf87c73c6ea5ed0"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.x86_64-linux-musl.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "4cd1aeef8997b04bf2866239fa2ff7320dd7de10"
os = "freebsd"

    [[OpenVAF.download]]
    sha256 = "663ac7e136b5bd2bc96347ed77c4c342b56c896595e2d54946b5baab96a9f8b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.x86_64-unknown-freebsd.tar.gz"
[[OpenVAF]]
arch = "x86_64"
git-tree-sha1 = "f0287af4a9a0cc7f5d34a3751b188c76bd5c0db1"
os = "windows"

    [[OpenVAF.download]]
    sha256 = "bc99cffab19e19f99045c81ef262e1c6cbb62af456a702074ceb6041c7027e21"
    url = "https://github.com/JuliaBinaryWrappers/OpenVAF_jll.jl/releases/download/OpenVAF-v23.5.0+0/OpenVAF.v23.5.0.x86_64-w64-mingw32.tar.gz"
